### ISSUE TITLE
Timestamp inconsistencies error bug, timestamp formatting error, and aws Unauthorized error

### ISSUE THREAD

**Issue by caaespin** [BD2KGenomics/dcc-ops#123]
related to #121

**Comment by achave11** [comment]
Timestamp formating do to pre-processing `datetime` objects in dual calls to the `calculate_compute` function, both formats are accounted for.

**Comment by achave11** [comment]
Closed by
https://github.com/BD2KGenomics/dcc-metadata-indexer/pull/91#pullrequestreview-70063869
