### ISSUE TITLE
Boardwalk deployed for HCA

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/dcc-ops#130]

**Comment by kozbo** [comment]
First step is to move repo to BD2KGenomics

**Comment by mikebaumann** [comment]
Focused title on deploying Boardwalk for HCA.
Boardwalk has been deployed sufficient for current Commons platform demo needs, and will track what is done for HCA going forward.

**Comment by natanlao** [comment]
Issue moved |
---|
This issue has been moved to [DataBiosphere/cgp-boardwalk#14](https://github.com/DataBiosphere/cgp-boardwalk/issues/14). |
