### ISSUE TITLE
Boardwalk - overview of work in 2018

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/dcc-ops#134]
CC wireframes demo

**Comment by natanlao** [comment]
Issue moved |
---|
This issue has been moved to [cgp-boardwalk/DataBiosphere#13](https://github.com/DataBiosphere/cgp-boardwalk/issues/13). |

**Comment by natanlao** [comment]
Issue moved |
---|
This issue has been moved to [cgp-deployment/DataBiosphere#17](https://github.com/DataBiosphere/cgp-deployment/issues/17). |

**Comment by natanlao** [comment]
Issue moved |
---|
This issue has been moved to [DataBiosphere/team-lighthouse-point#90](https://github.com/DataBiosphere/team-lighthouse-point/issues/90). |
