### ISSUE TITLE
Boardwalk backend Design doc

### ISSUE THREAD

**Issue by caaespin** [BD2KGenomics/dcc-ops#151]
Write a design doc with diagrams for the Boardwalk backend. It should be written such that it can be highly configured for different projects.

**Comment by cricketsloan** [comment]
This one is for the web service

**Comment by natanlao** [comment]
Issue moved |
---|
This issue has been moved to [cgp-boardwalk/DataBiosphere#12](https://github.com/DataBiosphere/cgp-boardwalk/issues/12). |
