### ISSUE TITLE
Persistance of redwood databases on VM shutdown and boot up

### ISSUE THREAD

**Issue by caaespin** [BD2KGenomics/dcc-ops#54]
Right now, if the system is shut down, the containers for the metadata and auth databases get destroyed, along with any data in it i believe (when the VM and redwood are brought up again, the registered tokens and metadata get cleared and so the containers are empty). This makes it hard to test if we want to shut down the VM at the end of the day in order to avoid costs. A way we could easily fix this is by mounting the data folder from each db defined in the `yml`file on the system by using the `volumes` tag and letting docker-compose mount the data in the local driver. 

See https://github.com/BD2KGenomics/dcc-ops/blob/develop/boardwalk/prod.yml 
and https://code.wiki/page/rkfuXEOq/Persist-data-in-MongoDB-with-Docker-Compose

I assume these changes will involve editing not only the `yml` but potentially the redwood cli. I think if it only does a `docker-compose down`, then we can just add the `-v` flag at the end to take down all the defined volumes in the `yml` with the upper level tag

**Comment by benjaminran** [comment]
You didn't call `redwood down`, but data was lost on restart?

**Comment by benjaminran** [comment]
I just tested and data persisted through restart just fine.

**Comment by benjaminran** [comment]
This shouldn't be an issue anymore. @caaespin, you can reopen this if it appears again
