### ISSUE TITLE
Redwood install_bootstrap not idempotent?

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/dcc-ops#63]
Beni, on a fresh install I’m still seeing failures to get redwood tokens via the dcc-ops process:

```
ubuntu@ip-172-31-62-97:~/dcc-ops$ sudo redwood/admin/bin/redwood token create -u myemail@ucsc.edu -s 'aws.upload aws.download'
{"timestamp":1494099619184,"status":500,"error":"Internal Server Error","exception":"org.springframework.jdbc.CannotGetJdbcConnectionException","message":"Could not get JDBC Connection; nested exception is org.postgresql.util.PSQLException: FATAL: password authentication failed for user \"dcc_auth\"","path":"/admin/scopes/myemail@ucsc.edu"}{"timestamp":1494099619271,"status":401,"error":"Unauthorized","message":"Could not get JDBC Connection; nested exception is org.postgresql.util.PSQLException: FATAL: password authentication failed for user \"dcc_auth\"","path":"/oauth/token"}
```

**Comment by briandoconnor** [comment]
Beni, I deleted all containers, images, volumes, tried the setup again (with the install line commented out) and the `redwood token create` command worked, producing a token.  So please try this when you re-run the install_bootstrapper a second time.  I think there’s something that causes problems on a second run?  Something that’s not idempotent in your code?

**Comment by benjaminran** [comment]
When redwood up is called, do you see a line of output like "recreating
redwood-auth-db"?

**Comment by briandoconnor** [comment]
I didn't notice... but next week go ahead and try to replicate this.

**Comment by benjaminran** [comment]
#42

**Comment by briandoconnor** [comment]
You'll need to expect people will run install_bootstrap mutliple times.  Needs to be able to deal with this gracefully.  And if it can't for some reason, then you need to give instructions in the README on how to avoid this problem.

**Comment by benjaminran** [comment]
`redwood up` shouldn't delete old data each time it's called, but the redwood installer definitely should start fresh, so in the commit above the installer now removes redwood data volumes if they exist

**Comment by benjaminran** [comment]
This should be fixed by the commits above. Reopen this if the error appears again
